// packages/vue-library/demo/components/DoiCard.vue
<script setup lang="ts">
import { PidComponent } from '../../lib';

defineProps<{
  value: string;
  license?: string;
}>();
</script>

<template>
  <v-card class="fill-height" elevation="1">
    <v-card-text>
      <div class="text-caption text-grey text-uppercase font-weight-bold mb-3">
        Digital Object Identifier
      </div>
      <pid-component :value="value" open-by-default="true" width="100%" style="display: block;" />
      <v-divider v-if="license" class="my-4"></v-divider>
      <template v-if="license">
        <div class="text-caption text-grey text-uppercase font-weight-bold mb-3">
          License
        </div>
        <pid-component :value="license" width="100%" style="display: block;" />
      </template>
    </v-card-text>
  </v-card>
</template>

// packages/angular-library/src/app/components/doi-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatDividerModule } from '@angular/material/divider';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-doi-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatDividerModule,
    PidComponent,
  ],
  template: `
    <mat-card class="doi-card">
      <mat-card-content>
        <h3 class="label">Digital Object Identifier</h3>
        <pid-component [value]="value" [openByDefault]="true" width="100%" />
        @if (license) {
          <mat-divider></mat-divider>
          <h3 class="label" style="margin-top: 16px">License</h3>
          <pid-component [value]="license" width="100%" />
        }
      </mat-card-content>
    </mat-card>
  `,
  styles: [`
    .doi-card {
      padding: 24px;
      height: 100%;
    }

    .label {
      font-size: 12px;
      font-weight: 600;
      color: #9e9e9e;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 12px;
    }
  `],
})
export class DoiCardComponent {
  @Input() value = '';
  @Input() license?: string;
}
