// packages/nextjs-app/app/research-nexus/components/Footer.tsx
import { Database } from 'lucide-react';

export function Footer() {
  return (
    <footer className="border-t border-slate-200 bg-white mt-12">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600">
              <Database className="h-4 w-4 text-white" />
            </div>
            <span className="text-sm font-semibold text-slate-900">ResearchDemo</span>
          </div>
          <p className="text-sm text-slate-500">
            Research Data Portal powered by KIT Data Manager
          </p>
        </div>
      </div>
    </footer>
  );
}

// packages/angular-library/src/app/components/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
  ],
  template: `
    <mat-toolbar color="primary" class="footer-toolbar">
      <div class="footer-container">
        <div class="footer-brand">
          <button mat-mini-fab color="accent" disabled>
            <mat-icon>storage</mat-icon>
          </button>
          <span class="brand-text">ResearchDemo</span>
        </div>
        <p class="footer-text">Research Data Portal powered by KIT Data Manager</p>
      </div>
    </mat-toolbar>
  `,
  styles: [`
    .footer-toolbar {
      margin-top: 48px;
      background: #212121;
    }

    .footer-container {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
      max-width: 1200px;
      margin: 0 auto;
    }

    .footer-brand {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .brand-text {
      font-size: 14px;
      font-weight: 600;
      color: white;
    }

    .footer-text {
      font-size: 14px;
      color: #9e9e9e;
      margin: 0;
    }
  `],
})
export class FooterComponent {
}
