// packages/react-library/demo/components/InteractiveComponents.tsx
'use client';

import { useState } from 'react';
import { Paper, Text, Badge, Progress, Group } from '@mantine/core';

const contentTypes = ['Datasets', 'Publications', 'Software', 'Workflows'] as const;

export function ContentTypeToggles() {
  const [active, setActive] = useState<string>('Datasets');

  return (
    <Paper shadow="sm" padding="lg" radius="md" withBorder>
      <Text fw={600} size="sm" mb={4}>Content Type Toggles</Text>
      <Text size="xs" c="dimmed" mb="md">
        These toggles maintain state independently of the autodetection
        running above. React state is not blocked by DOM tree traversal.
      </Text>
      <Group gap="xs">
        {contentTypes.map((type) => (
          <Badge
            key={type}
            component="button"
            onClick={() => setActive(type)}
            size="lg"
            variant={active === type ? 'filled' : 'outline'}
            color={active === type ? 'indigo' : 'gray'}
            style={{ cursor: 'pointer' }}
          >
            {type}
          </Badge>
        ))}
      </Group>
      <Text size="xs" c="dimmed" mt="md">
        Selected: {active}
      </Text>
    </Paper>
  );
}

export function ProgressIndicators() {
  return (
    <Paper shadow="sm" padding="lg" radius="md" withBorder>
      <Text fw={600} size="sm" mb={4}>Download Progress</Text>
      <Text size="xs" c="dimmed" mb="md">
        Progress updates work while autodetection runs above.
        requestAnimationFrame is not blocked.
      </Text>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <div>
          <Group justify="space-between" mb={4}>
            <Text size="xs">Dataset download</Text>
            <Text size="xs" c="dimmed">73%</Text>
          </Group>
          <Progress value={73} color="green" size="sm" radius="xl" />
        </div>
        <div>
          <Group justify="space-between" mb={4}>
            <Text size="xs">Metadata extraction</Text>
            <Text size="xs" c="dimmed">45%</Text>
          </Group>
          <Progress value={45} color="indigo" size="sm" radius="xl" />
        </div>
        <div>
          <Group justify="space-between" mb={4}>
            <Text size="xs">Validation</Text>
            <Text size="xs" c="dimmed">12%</Text>
          </Group>
          <Progress value={12} color="yellow" size="sm" radius="xl" />
        </div>
      </div>
    </Paper>
  );
}

// packages/angular-library/src/app/components/interactive-components.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressBarModule } from '@angular/material/progress-bar';

@Component({
  selector: 'app-content-toggles',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatChipsModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Content Type Toggles</h3>
      <p class="card-description">
        These toggles maintain state independently of the autodetection
        running above. Angular state is not blocked by DOM tree traversal.
      </p>
      <mat-chip-set>
        @for (type of contentTypes; track type) {
          <mat-chip
            [highlighted]="activeType === type"
            (click)="selectType(type)"
            class="toggle-chip">
            {{ type }}
          </mat-chip>
        }
      </mat-chip-set>
      <p class="card-footer">Selected: {{ activeType }}</p>
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .card-footer {
      font-size: 12px;
      color: #9e9e9e;
      margin: 16px 0 0 0;
    }

    .toggle-chip {
      cursor: pointer;
    }
  `],
})
export class ContentTogglesComponent {
  contentTypes = ['Datasets', 'Publications', 'Software', 'Workflows'];
  activeType = 'Datasets';

  selectType(type: string) {
    this.activeType = type;
  }
}

@Component({
  selector: 'app-progress-indicators',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatProgressBarModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Download Progress</h3>
      <p class="card-description">
        Progress updates work while autodetection runs above.
        requestAnimationFrame is not blocked.
      </p>
      <div class="progress-item">
        <div class="progress-label">
          <span>Dataset download</span>
          <span>73%</span>
        </div>
        <mat-progress-bar mode="determinate" value="73" color="primary"></mat-progress-bar>
      </div>
      <div class="progress-item">
        <div class="progress-label">
          <span>Metadata extraction</span>
          <span>45%</span>
        </div>
        <mat-progress-bar mode="determinate" value="45" color="accent"></mat-progress-bar>
      </div>
      <div class="progress-item">
        <div class="progress-label">
          <span>Validation</span>
          <span>12%</span>
        </div>
        <mat-progress-bar mode="determinate" value="12" color="warn"></mat-progress-bar>
      </div>
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .progress-item {
      margin-bottom: 16px;
    }

    .progress-item:last-child {
      margin-bottom: 0;
    }

    .progress-label {
      display: flex;
      justify-content: space-between;
      margin-bottom: 4px;
      font-size: 12px;
      color: #424242;
    }
  `],
})
export class ProgressIndicatorsComponent {
}
