// packages/react-library/demo/components/InteractiveFilters.tsx
'use client';

import { useState, type MouseEvent, type FormEvent } from 'react';
import { Paper, Text, TextInput, Select, Button, Group, Badge } from '@mantine/core';
import { IconSortAscending } from '@tabler/icons-react';

const defaultDatasets = [
  { id: 1, name: 'Dataset A - 1,234 items', active: true },
  { id: 2, name: 'Dataset B - 567 items', active: true },
  { id: 3, name: 'Dataset C - 2,891 items', active: true },
  { id: 4, name: 'Dataset D - 432 items', active: false },
];

export function SortableList() {
  const [datasets, setDatasets] = useState(defaultDatasets);

  const toggleActive = (id: number) => {
    setDatasets(datasets.map(d =>
      d.id === id ? { ...d, active: !d.active } : d,
    ));
  };

  return (
    <Paper shadow="sm" padding="lg" radius="md" withBorder>
      <Text fw={600} size="sm" mb={4}>Sortable Dataset List</Text>
      <Text size="xs" c="dimmed" mb="md">
        This list is fully interactive - sorting works immediately while
        autodetection runs above. DOM tree traversal does not block event handlers.
      </Text>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {datasets.map((dataset) => (
          <Group
            key={dataset.id}
            onClick={() => toggleActive(dataset.id)}
            justify="space-between"
            style={{
              cursor: 'pointer',
              backgroundColor: '#f8f9fa',
              padding: '8px 12px',
              borderRadius: 8,
            }}
          >
            <Group gap="xs">
              <Badge
                size="xs"
                circle
                color={dataset.active ? 'green' : 'gray'}
              />
              <Text size="sm">{dataset.name}</Text>
            </Group>
            <Button
              size="xs"
              variant="light"
              color="indigo"
              leftSection={<IconSortAscending size={12} />}
              onClick={(e: MouseEvent) => {
                e.stopPropagation();
              }}
            >
              Sort
            </Button>
          </Group>
        ))}
      </div>
      <Text size="xs" c="dimmed" mt="md">
        Active datasets: {datasets.filter(d => d.active).length}
      </Text>
    </Paper>
  );
}

export function FilterForm() {
  const [search, setSearch] = useState('');
  const [dateRange, setDateRange] = useState<string | null>('30');
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    setSubmitted(true);
  };

  return (
    <Paper shadow="sm" padding="lg" radius="md" withBorder>
      <Text fw={600} size="sm" mb={4}>Dataset Filter</Text>
      <Text size="xs" c="dimmed" mb="md">
        This form is fully functional while autodetection runs above.
        Input events and state updates work immediately.
      </Text>
      <form onSubmit={handleSubmit}>
        <TextInput
          label="Dataset Name"
          placeholder="Search datasets..."
          value={search}
          onChange={(e) => setSearch(e.currentTarget.value)}
          mb="md"
          size="sm"
        />
        <Select
          label="Date Range"
          data={[
            { value: '7', label: 'Last 7 days' },
            { value: '30', label: 'Last 30 days' },
            { value: '90', label: 'Last 90 days' },
            { value: 'all', label: 'All time' },
          ]}
          value={dateRange}
          onChange={setDateRange}
          mb="md"
          size="sm"
        />
        <Button type="submit" color="indigo" fullWidth>
          Apply Filters
        </Button>
      </form>
      {submitted && (
        <Text size="xs" c="green" mt="md">
          Filters applied! Search: "{search}", Range: {dateRange}
        </Text>
      )}
    </Paper>
  );
}

// packages/angular-library/src/app/components/interactive-filters.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatListModule } from '@angular/material/list';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';

interface Dataset {
  id: number;
  name: string;
  active: boolean;
}

@Component({
  selector: 'app-sortable-list',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatListModule,
    MatButtonModule,
    MatIconModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Sortable Dataset List</h3>
      <p class="card-description">
        This list is fully interactive - sorting works immediately while
        autodetection runs above. DOM tree traversal does not block event handlers.
      </p>
      <mat-list>
        @for (dataset of datasets; track dataset.id) {
          <mat-list-item [class.inactive]="!dataset.active">
            <span matListItemIcon [class]="'dot ' + (dataset.active ? 'active' : 'inactive')"></span>
            <span matListItemTitle>{{ dataset.name }}</span>
            <button mat-button color="primary" matListItemMeta>
              <mat-icon>sort</mat-icon>
              Sort
            </button>
          </mat-list-item>
        }
      </mat-list>
      <p class="card-footer">Active datasets: {{ activeCount }}</p>
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .card-footer {
      font-size: 12px;
      color: #9e9e9e;
      margin: 16px 0 0 0;
    }

    mat-list-item {
      margin-bottom: 8px;
      background: #fafafa;
      border-radius: 8px;
    }

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
    }

    .dot.active {
      background: #4caf50;
    }

    .dot.inactive {
      background: #bdbdbd;
    }
  `],
})
export class SortableListComponent {
  datasets: Dataset[] = [
    { id: 1, name: 'Dataset A - 1,234 items', active: true },
    { id: 2, name: 'Dataset B - 567 items', active: true },
    { id: 3, name: 'Dataset C - 2,891 items', active: true },
    { id: 4, name: 'Dataset D - 432 items', active: false },
  ];

  get activeCount(): number {
    return this.datasets.filter(d => d.active).length;
  }
}

@Component({
  selector: 'app-filter-form',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Dataset Filter</h3>
      <p class="card-description">
        This form is fully functional while autodetection runs above.
        Input events and state updates work immediately.
      </p>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Dataset Name</mat-label>
        <input matInput [(ngModel)]="searchQuery" placeholder="Search datasets..." />
      </mat-form-field>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Date Range</mat-label>
        <mat-select [(ngModel)]="dateRange">
          <mat-option value="7">Last 7 days</mat-option>
          <mat-option value="30">Last 30 days</mat-option>
          <mat-option value="90">Last 90 days</mat-option>
          <mat-option value="all">All time</mat-option>
        </mat-select>
      </mat-form-field>
      <button mat-flat-button color="primary" (click)="applyFilters()" class="full-width">
        Apply Filters
      </button>
      @if (submitted) {
        <p class="card-footer success">
          Filters applied! Search: "{{ searchQuery }}", Range: {{ dateRangeLabel }}
        </p>
      }
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .card-footer {
      font-size: 12px;
      color: #9e9e9e;
      margin: 16px 0 0 0;
    }

    .card-footer.success {
      color: #4caf50;
    }

    .full-width {
      width: 100%;
      margin-bottom: 8px;
    }
  `],
})
export class FilterFormComponent {
  searchQuery = '';
  dateRange = '30';
  submitted = false;

  get dateRangeLabel(): string {
    const labels: Record<string, string> = {
      '7': 'Last 7 days',
      '30': 'Last 30 days',
      '90': 'Last 90 days',
      'all': 'All time',
    };
    return labels[this.dateRange] || this.dateRange;
  }

  applyFilters() {
    this.submitted = true;
  }
}
