// packages/nextjs-app/app/research-nexus/components/InteractiveFilters.tsx
'use client';

import { useState } from 'react';
import { cn } from '../lib/utils';

export function SortableList() {
  const [items] = useState([
    { id: 1, name: 'Dataset A - 1,234 items', active: true },
    { id: 2, name: 'Dataset B - 567 items', active: true },
    { id: 3, name: 'Dataset C - 2,891 items', active: true },
    { id: 4, name: 'Dataset D - 432 items', active: false },
  ]);

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h3 className="text-sm font-semibold text-slate-900 mb-1">Sortable Dataset List</h3>
      <p className="text-xs text-slate-500 mb-4">
        This list is fully interactive - sorting works immediately while
        autodetection runs above. DOM tree traversal does not block event handlers.
      </p>
      <div className="space-y-2">
        {items.map((item) => (
          <div
            key={item.id}
            className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 hover:bg-slate-100 cursor-pointer transition-colors"
          >
            <div className={cn('h-2 w-2 rounded-full', item.active ? 'bg-emerald-500' : 'bg-slate-300')} />
            <span className="flex-1 text-sm text-slate-700">{item.name}</span>
            <button
              className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md border border-indigo-200 bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 transition-colors hover:bg-indigo-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-700 disabled:pointer-events-none disabled:opacity-50">
              Sort
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

export function FilterForm() {
  const [search, setSearch] = useState('');
  const [dateRange, setDateRange] = useState('30');

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h3 className="text-sm font-semibold text-slate-900 mb-1">Dataset Filter</h3>
      <p className="text-xs text-slate-500 mb-4">
        This form is fully functional while autodetection runs above.
        Input events and state updates work immediately.
      </p>
      <div className="space-y-3">
        <div>
          <label className="text-xs font-medium text-slate-700 mb-1 block">Dataset Name</label>
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search datasets..."
            className="flex h-9 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm ring-offset-white placeholder:text-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-700 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          />
        </div>
        <div>
          <label className="text-xs font-medium text-slate-700 mb-1 block">Date Range</label>
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
            className="flex h-9 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm ring-offset-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-700 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <option value="7">Last 7 days</option>
            <option value="30">Last 30 days</option>
            <option value="90">Last 90 days</option>
            <option value="all">All time</option>
          </select>
        </div>
        <button
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-700 disabled:pointer-events-none disabled:opacity-50 w-full">
          Apply Filters
        </button>
      </div>
    </div>
  );
}

// packages/angular-library/src/app/components/interactive-filters.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatListModule } from '@angular/material/list';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';

interface Dataset {
  id: number;
  name: string;
  active: boolean;
}

@Component({
  selector: 'app-sortable-list',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatListModule,
    MatButtonModule,
    MatIconModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Sortable Dataset List</h3>
      <p class="card-description">
        This list is fully interactive - sorting works immediately while
        autodetection runs above. DOM tree traversal does not block event handlers.
      </p>
      <mat-list>
        @for (dataset of datasets; track dataset.id) {
          <mat-list-item [class.inactive]="!dataset.active">
            <span matListItemIcon [class]="'dot ' + (dataset.active ? 'active' : 'inactive')"></span>
            <span matListItemTitle>{{ dataset.name }}</span>
            <button mat-button color="primary" matListItemMeta>
              <mat-icon>sort</mat-icon>
              Sort
            </button>
          </mat-list-item>
        }
      </mat-list>
      <p class="card-footer">Active datasets: {{ activeCount }}</p>
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .card-footer {
      font-size: 12px;
      color: #9e9e9e;
      margin: 16px 0 0 0;
    }

    mat-list-item {
      margin-bottom: 8px;
      background: #fafafa;
      border-radius: 8px;
    }

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
    }

    .dot.active {
      background: #4caf50;
    }

    .dot.inactive {
      background: #bdbdbd;
    }
  `],
})
export class SortableListComponent {
  datasets: Dataset[] = [
    { id: 1, name: 'Dataset A - 1,234 items', active: true },
    { id: 2, name: 'Dataset B - 567 items', active: true },
    { id: 3, name: 'Dataset C - 2,891 items', active: true },
    { id: 4, name: 'Dataset D - 432 items', active: false },
  ];

  get activeCount(): number {
    return this.datasets.filter(d => d.active).length;
  }
}

@Component({
  selector: 'app-filter-form',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
  ],
  template: `
    <mat-card class="interactive-card">
      <h3 class="card-title">Dataset Filter</h3>
      <p class="card-description">
        This form is fully functional while autodetection runs above.
        Input events and state updates work immediately.
      </p>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Dataset Name</mat-label>
        <input matInput [(ngModel)]="searchQuery" placeholder="Search datasets..." />
      </mat-form-field>
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Date Range</mat-label>
        <mat-select [(ngModel)]="dateRange">
          <mat-option value="7">Last 7 days</mat-option>
          <mat-option value="30">Last 30 days</mat-option>
          <mat-option value="90">Last 90 days</mat-option>
          <mat-option value="all">All time</mat-option>
        </mat-select>
      </mat-form-field>
      <button mat-flat-button color="primary" (click)="applyFilters()" class="full-width">
        Apply Filters
      </button>
      @if (submitted) {
        <p class="card-footer success">
          Filters applied! Search: "{{ searchQuery }}", Range: {{ dateRangeLabel }}
        </p>
      }
    </mat-card>
  `,
  styles: [`
    .interactive-card {
      padding: 20px;
    }

    .card-title {
      font-size: 14px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
    }

    .card-description {
      font-size: 12px;
      color: #9e9e9e;
      margin: 0 0 16px 0;
    }

    .card-footer {
      font-size: 12px;
      color: #9e9e9e;
      margin: 16px 0 0 0;
    }

    .card-footer.success {
      color: #4caf50;
    }

    .full-width {
      width: 100%;
      margin-bottom: 8px;
    }
  `],
})
export class FilterFormComponent {
  searchQuery = '';
  dateRange = '30';
  submitted = false;

  get dateRangeLabel(): string {
    const labels: Record<string, string> = {
      '7': 'Last 7 days',
      '30': 'Last 30 days',
      '90': 'Last 90 days',
      'all': 'All time',
    };
    return labels[this.dateRange] || this.dateRange;
  }

  applyFilters() {
    this.submitted = true;
  }
}
