// packages/vue-library/demo/components/DatasetsPage.vue
<script setup lang="ts">
import { ref, inject } from 'vue';
import type { PidDetectionController } from '@kit-data-manager/pid-component';

defineProps<{
  excludeArticleRef?: boolean;
}>();

const articleRef = inject<{
  controller: PidDetectionController | null;
  root: HTMLElement | null;
  isActive: boolean
}>('autodiscovery');

const headers = [
  { title: 'ID', key: 'id', align: 'start' as const },
  { title: 'Title', key: 'title', align: 'start' as const },
  { title: 'DOI', key: 'doi', align: 'start' as const },
  { title: 'License', key: 'license', align: 'start' as const },
];

const datasets = ref([
  {
    id: '1',
    title: 'KIT Data Metadata Analysis',
    doi: '10.5445/IR/1000185135',
    license: 'https://spdx.org/licenses/MIT',
  },
  {
    id: '2',
    title: 'Research Output Repository Schema',
    doi: '10.5445/IR/1000178054',
    license: 'https://spdx.org/licenses/Apache-2.0',
  },
  {
    id: '3',
    title: 'FDO Implementation Guidelines',
    doi: '10.5445/IR/1000151234',
    license: 'https://spdx.org/licenses/CC-BY-4.0',
  },
]);
</script>

<template>
  <div class="mb-8">
    <h2 class="text-h6 font-weight-bold mb-4 d-flex align-center">
      <v-icon color="primary" class="mr-2">mdi-database</v-icon>
      Dataset Overview
      <v-chip color="primary-lighten-5" text-color="primary-darken-2" size="small" class="ml-3">
        {{ articleRef?.isActive ? 'Scanning Active' : 'Scanning Inactive' }}
      </v-chip>
    </h2>
    <v-card class="pa-6" elevation="1">
      <v-data-table
        :headers="headers"
        :items="datasets"
        :items-per-page="5"
        class="elevation-0"
      >
        <template v-slot:item.doi="{ item }">
          <pid-component :value="item.doi" :open-by-default="false" />
        </template>
        <template v-slot:item.license="{ item }">
          <pid-component :value="item.license" :open-by-default="false" />
        </template>
      </v-data-table>
    </v-card>
  </div>
</template>

// packages/react-library/demo/components/DatasetsPage.tsx
'use client';

import { useState } from 'react';
import { Badge, Card, Table, Title } from '@mantine/core';
import { PidComponent } from '../../lib';

interface DatasetsPageProps {
}

export function DatasetsPage({}: DatasetsPageProps) {
  const [isActive] = useState(false);

  const headers = ['ID', 'Title', 'DOI', 'License'];
  const datasets = [
    {
      id: '1',
      title: 'KIT Data Metadata Analysis',
      doi: '10.5445/IR/1000185135',
      license: 'https://spdx.org/licenses/MIT',
    },
    {
      id: '2',
      title: 'Research Output Repository Schema',
      doi: '10.5445/IR/1000178054',
      license: 'https://spdx.org/licenses/Apache-2.0',
    },
    {
      id: '3',
      title: 'FDO Implementation Guidelines',
      doi: '10.5445/IR/1000151234',
      license: 'https://spdx.org/licenses/CC-BY-4.0',
    },
  ];

  return (
    <div style={{ marginBottom: 32 }}>
      <Title order={2} mb="md" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        Dataset Overview
        <Badge color={isActive ? 'green' : 'red'} variant="light" size="sm">
          {isActive ? 'Scanning Active' : 'Scanning Inactive'}
        </Badge>
      </Title>
      <Card shadow="sm" padding="xl" radius="md" withBorder>
        <Table striped highlightOnHover>
          <Table.Thead>
            <Table.Tr>
              {headers.map(h => <Table.Th key={h}>{h}</Table.Th>)}
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {datasets.map(item => (
              <Table.Tr key={item.id}>
                <Table.Td>{item.id}</Table.Td>
                <Table.Td>{item.title}</Table.Td>
                <Table.Td><PidComponent value={item.doi} openByDefault={false} /></Table.Td>
                <Table.Td><PidComponent value={item.license} openByDefault={false} /></Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      </Card>
    </div>
  );
}
