// packages/vue-library/demo/components/LicenseDialog.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { PidComponent } from '../../lib';

const dialogOpen = ref(false);

const openDialog = () => {
  dialogOpen.value = true;
};
</script>

<template>
  <v-card class="fill-height" elevation="1">
    <v-card-item>
      <v-card-title class="text-body-1 font-weight-bold d-flex align-center ga-2">
        <v-icon color="grey-darken-2">mdi-scale-balance</v-icon>
        License Information
      </v-card-title>
    </v-card-item>
    <v-card-text>
      <v-btn color="primary" @click="openDialog">
        <v-icon start>mdi-scale-balance</v-icon>
        View License Details
      </v-btn>
    </v-card-text>
  </v-card>

  <v-dialog v-model="dialogOpen" max-width="600">
    <v-card>
      <v-card-title class="text-h6 font-weight-bold">Apache License 2.0</v-card-title>
      <v-card-text>
        <p class="text-body-2 text-grey mb-4">
          This dataset is published under the Apache 2.0 license, allowing free reuse with appropriate attribution.
        </p>
        <pid-component open-by-default="true" style="display: block;" value="https://spdx.org/licenses/Apache-2.0"
                       width="100%" />
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn color="grey" variant="outlined" @click="dialogOpen = false">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

// packages/react-library/demo/components/LicenseDialog.tsx
'use client';

import { useState } from 'react';
import { Paper, Modal, Button, Text, Group } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconScale } from '@tabler/icons-react';
import { PidComponent } from '../../lib';

export function LicenseDialog() {
  const [opened, { open, close }] = useDisclosure(false);

  return (
    <>
      <Paper shadow="sm" padding="xl" radius="md" withBorder>
        <Text fw={600} size="md" mb="md" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <IconScale size={20} />
          License Information
        </Text>
        <Button onClick={open} color="indigo" leftSection={<IconScale size={16} />}>
          View License Details
        </Button>
      </Paper>

      <Modal
        opened={opened}
        onClose={close}
        title="Apache License 2.0"
        centered
        size="md"
      >
        <Text size="sm" c="dimmed" mb="md">
          This dataset is published under the Apache 2.0 license, allowing free reuse
          with appropriate attribution.
        </Text>
        <PidComponent value="https://spdx.org/licenses/Apache-2.0" openByDefault={true} width="100%" />
        <Group justify="flex-end" mt="xl">
          <Button variant="outline" color="gray" onClick={close}>
            Close
          </Button>
        </Group>
      </Modal>
    </>
  );
}
