// packages/react-library/demo/components/AuthorCard.tsx
'use client';

import { Paper, Avatar, Group, Stack, Text } from '@mantine/core';
import { PidComponent } from '../../lib';

interface Author {
  orcid: string;
  name: string;
  role?: string;
  institution?: string;
}

interface AuthorCardProps {
  author: Author;
}

export function AuthorCard({ author }: AuthorCardProps) {
  const initials = author.name.split(' ').map(n => n[0]).join('');

  return (
    <Paper shadow="sm" padding="lg" radius="md" withBorder>
      <Group gap="md" align="flex-start">
        <Avatar size={48} radius="xl" color="indigo">
          {initials}
        </Avatar>
        <Stack gap={4} style={{ flex: 1 }}>
          <Text fw={600} size="sm">{author.name}</Text>
          <Text size="xs" c="dimmed">{author.role}</Text>
          {author.institution && (
            <Text size="xs" c="dimmed" style={{ color: '#9ca3af' }}>{author.institution}</Text>
          )}
          <div style={{ marginTop: 8 }}>
            <PidComponent value={author.orcid} emphasizeComponent={false} />
          </div>
        </Stack>
      </Group>
    </Paper>
  );
}

interface AuthorGridProps {
  authors: Author[];
}

export function AuthorGrid({ authors }: AuthorGridProps) {
  return (
    <div style={{ marginBottom: 32 }}>
      <Text fw={600} size="md" mb="md" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        Developers of the pid-component
      </Text>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
        {authors.map((author) => (
          <AuthorCard key={author.orcid} author={author} />
        ))}
      </div>
    </div>
  );
}

// packages/vue-library/demo/components/AuthorCard.vue
<script lang="ts">
export interface Author {
  orcid: string;
  name: string;
  institution?: string;
}
</script>

<script setup lang="ts">
defineProps<{
  author: Author;
}>();

const getInitials = (name: string): string => {
  return name.split(' ').map(n => n[0]).join('');
};
</script>

<template>
  <v-card elevation="1">
    <v-card-text>
      <div class="d-flex align-start ga-4">
        <v-avatar color="indigo-lighten-5" size="48" class="flex-shrink-0">
          <span class="text-indigo-darken-2 font-weight-bold">{{ getInitials(author.name) }}</span>
        </v-avatar>
        <div class="flex-grow-1">
          <div class="text-body-1 font-weight-bold">{{ author.name }}</div>
          <div v-if="author.institution" class="text-caption text-grey-lighten-1 mb-2">
            {{ author.institution }}
          </div>
          <pid-component :value="author.orcid" :emphasize-component="false" style="display: block;" />
        </div>
      </div>
    </v-card-text>
  </v-card>
</template>
