// packages/react-library/demo/components/DatasetTable.tsx
'use client';

import { useRef, useCallback } from 'react';
import { Paper, Table, Button, Group, Text } from '@mantine/core';
import { IconFileText } from '@tabler/icons-react';
import { PidComponent } from '../../lib';

interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

interface DatasetTableProps {
  datasets: Dataset[];
}

/** Minimal column-resize hook – drag the right edge of a <th> to resize. */
function useColumnResize() {
  const tableRef = useRef<HTMLTableElement>(null);

  const onMouseDown = useCallback((colIndex: number, e: React.MouseEvent) => {
    e.preventDefault();
    const table = tableRef.current;
    if (!table) return;
    const th = table.querySelectorAll('th')[colIndex] as HTMLTableCellElement;
    if (!th) return;

    const startX = e.clientX;
    const startWidth = th.offsetWidth;

    const onMouseMove = (moveEvent: MouseEvent) => {
      const newWidth = Math.max(60, startWidth + moveEvent.clientX - startX);
      th.style.width = `${newWidth}px`;
    };
    const onMouseUp = () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  }, []);

  return { tableRef, onMouseDown };
}

const thStyle: React.CSSProperties = {
  fontWeight: 600,
  fontSize: 12,
  textTransform: 'uppercase',
  color: '#6b7280',
  position: 'relative',
  overflow: 'hidden',
};

const resizeHandleStyle: React.CSSProperties = {
  position: 'absolute',
  right: 0,
  top: 0,
  bottom: 0,
  width: 5,
  cursor: 'col-resize',
  userSelect: 'none',
};

export function DatasetTable({ datasets }: DatasetTableProps) {
  const { tableRef, onMouseDown } = useColumnResize();

  return (
    <Paper shadow="sm" padding={0} radius="md" withBorder style={{ overflow: 'hidden' }}>
      <div style={{ padding: '20px 24px', borderBottom: '1px solid #e0e0e0' }}>
        <Group gap="xs">
          <IconFileText size={20} color="#6366f1" />
          <Text fw={600} size="md">Related Datasets</Text>
        </Group>
      </div>
      <div style={{ overflowX: 'auto' }}>
        <Table striped highlightOnHover ref={tableRef} style={{ tableLayout: 'fixed', width: '100%' }}>
          <Table.Thead>
            <Table.Tr style={{ backgroundColor: '#f8f9fa' }}>
              <Table.Th style={{ ...thStyle, width: '30%' }}>
                Title
                <span style={resizeHandleStyle} onMouseDown={(e) => onMouseDown(0, e)} />
              </Table.Th>
              <Table.Th style={{ ...thStyle, width: '30%' }}>
                DOI
                <span style={resizeHandleStyle} onMouseDown={(e) => onMouseDown(1, e)} />
              </Table.Th>
              <Table.Th style={{ ...thStyle, width: '25%' }}>
                License
                <span style={resizeHandleStyle} onMouseDown={(e) => onMouseDown(2, e)} />
              </Table.Th>
              <Table.Th style={{ ...thStyle, width: '15%' }}>Actions</Table.Th>
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {datasets.map((dataset) => (
              <Table.Tr key={dataset.id}>
                <Table.Td style={{
                  fontSize: 14,
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}>{dataset.title}</Table.Td>
                <Table.Td style={{ overflow: 'hidden' }}><PidComponent value={dataset.doi} emphasizeComponent={false} /></Table.Td>
                <Table.Td style={{ overflow: 'hidden' }}><PidComponent value={dataset.license}
                                                                       emphasizeComponent={false} /></Table.Td>
                <Table.Td>
                  <Button variant="subtle" color="gray" size="xs">View</Button>
                </Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      </div>
    </Paper>
  );
}

// packages/vue-library/demo/components/DatasetTable.vue
<script setup lang="ts">
import { PidComponent } from '../../lib';
import { ref, reactive } from 'vue';

interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

defineProps<{
  datasets: Dataset[];
}>();

const columnWidths = reactive<Record<string, number>>({
  title: 30,
  doi: 30,
  license: 25,
  actions: 15,
});

let resizing: { key: string; startX: number; startWidth: number } | null = null;

function onResizeStart(event: MouseEvent, key: string) {
  event.preventDefault();
  resizing = { key, startX: event.clientX, startWidth: columnWidths[key] };
  document.addEventListener('mousemove', onResizeMove);
  document.addEventListener('mouseup', onResizeEnd);
}

function onResizeMove(event: MouseEvent) {
  if (!resizing) return;
  const table = document.querySelector('.dataset-table-inner') as HTMLElement | null;
  if (!table) return;
  const tableWidth = table.offsetWidth;
  const deltaPercent = ((event.clientX - resizing.startX) / tableWidth) * 100;
  const newWidth = Math.max(5, resizing.startWidth + deltaPercent);
  columnWidths[resizing.key] = newWidth;
}

function onResizeEnd() {
  resizing = null;
  document.removeEventListener('mousemove', onResizeMove);
  document.removeEventListener('mouseup', onResizeEnd);
}
</script>

<template>
  <v-card elevation="1" style="overflow: hidden">
    <v-card-title class="d-flex align-center pa-4 border-b">
      <v-icon color="grey-darken-2" class="mr-2">mdi-file-document</v-icon>
      <span class="text-h6">Related Datasets</span>
    </v-card-title>
    <div style="overflow-x: auto">
      <v-table class="dataset-table-inner elevation-0" style="table-layout: fixed; width: 100%">
        <thead>
        <tr>
          <th
            v-for="col in [
                { key: 'title', label: 'Title' },
                { key: 'doi', label: 'DOI' },
                { key: 'license', label: 'License' },
                { key: 'actions', label: 'Actions' },
              ]"
            :key="col.key"
            :style="{ width: columnWidths[col.key] + '%', position: 'relative', userSelect: 'none' }"
          >
            {{ col.label }}
            <span
              class="resize-handle"
              @mousedown.prevent="onResizeStart($event, col.key)"
            ></span>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="item in datasets" :key="item.id">
          <td style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{ item.title }}</td>
          <td style="overflow: hidden">
            <pid-component :value="item.doi" :emphasize-component="false" style="display: inline-block;" />
          </td>
          <td style="overflow: hidden">
            <pid-component :value="item.license" :emphasize-component="false" style="display: inline-block;" />
          </td>
          <td style="overflow: hidden">
            <v-btn size="small" variant="text" color="primary">View</v-btn>
          </td>
        </tr>
        </tbody>
      </v-table>
    </div>
  </v-card>
</template>

<style scoped>
.resize-handle {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 4px;
  cursor: col-resize;
  background: transparent;
}

.resize-handle:hover {
  background: #90caf9;
}
</style>
