// packages/nextjs-app/app/research-nexus/page.tsx
import { Navigation } from './components/Navigation';
import { HeroCard, DoiCard } from './components/HeroCard';
import { DatasetTable } from './components/DatasetTable';
import { AuthorGrid } from './components/AuthorCard';
import { ArticleSection } from './components/ArticleSection';
import { SortableList, FilterForm } from './components/InteractiveFilters';
import { ContentTypeToggles, ProgressIndicators } from './components/InteractiveComponents';
import { LicenseDialog } from './components/LicenseDialog';
import { Footer } from './components/Footer';

const datasets = [
  {
    id: '1',
    title: 'KIT Data Metadata Analysis',
    doi: '10.5445/IR/1000185135',
    license: 'https://spdx.org/licenses/MIT',
  },
  {
    id: '2',
    title: 'Research Output Repository Schema',
    doi: '10.5445/IR/1000178054',
    license: 'https://spdx.org/licenses/Apache-2.0',
  },
  {
    id: '3',
    title: 'FDO Implementation Guidelines',
    doi: '10.5445/IR/1000151234',
    license: 'https://spdx.org/licenses/CC-BY-4.0',
  },
];

const authors = [
  { orcid: '0009-0005-2800-4833', name: 'Maximilian Inckmann', institution: 'Karlsruhe Institute of Technology' },
  { orcid: '0009-0003-2196-9187', name: 'Christopher Raquet', institution: 'Karlsruhe Institute of Technology' },
  { orcid: '0000-0001-6575-1022', name: 'Andreas Pfeil', institution: 'Karlsruhe Institute of Technology' },
];

export default function ResearchDemoPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Navigation />

      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-3 gap-6 mb-8">
          <HeroCard
            className="col-span-2"
            title="Comprehensive Analysis of Persistent Identifier Systems in FAIR Digital Objects"
            description="This dataset contains the complete analysis of PID systems including Handle, DOI, and ORCID integrations across major research institutions. Published in IEEE eScience 2025."
          />
          <DoiCard
            value="10.1109/eScience65000.2025.00022"
            license="https://spdx.org/licenses/Apache-2.0"
          />
        </div>

        <DatasetTable datasets={datasets} className="mb-8" />

        <AuthorGrid authors={authors} />

        <ArticleSection />

        <div className="mb-8">
          <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2 mb-4">
            Interactive Components
            <span
              className="inline-flex items-center rounded-full border border-amber-200 bg-amber-50 px-2.5 py-0.5 text-xs font-semibold text-amber-700">
              Working Below Autodetection
            </span>
          </h2>
          <div className="grid grid-cols-2 gap-4">
            <SortableList />
            <FilterForm />
            <ContentTypeToggles />
            <ProgressIndicators />
          </div>
        </div>

        <LicenseDialog />
      </main>

      <Footer />
    </div>
  );
}

// packages/angular-library/src/app/research-nexus.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NavigationComponent,
  HeroCardComponent,
  DoiCardComponent,
  DatasetTableComponent,
  Dataset,
  AuthorGridComponent,
  Author,
  ArticleSectionComponent,
  SortableListComponent,
  FilterFormComponent,
  ContentTogglesComponent,
  ProgressIndicatorsComponent,
  LicenseDialogComponent,
  FooterComponent,
} from './components';

@Component({
  selector: 'app-research-nexus',
  standalone: true,
  imports: [
    CommonModule,
    NavigationComponent,
    HeroCardComponent,
    DoiCardComponent,
    DatasetTableComponent,
    AuthorGridComponent,
    ArticleSectionComponent,
    SortableListComponent,
    FilterFormComponent,
    ContentTogglesComponent,
    ProgressIndicatorsComponent,
    LicenseDialogComponent,
    FooterComponent,
  ],
  template: `
    <div class="research-nexus-app">
      <app-navigation [activePage]="activePage" (navigate)="onNavigate($event)" />

      <main class="main-content">
        <div class="container">
          <div class="hero-grid">
            <div class="hero-main">
              <app-hero-card
                title="Comprehensive Analysis of Persistent Identifier Systems in FAIR Digital Objects"
                description="This dataset contains the complete analysis of PID systems including Handle, DOI, and ORCID integrations across major research institutions. Published in IEEE eScience 2025."
              />
            </div>
            <div class="hero-doi">
              <app-doi-card
                value="10.1109/eScience65000.2025.00022"
                license="https://spdx.org/licenses/Apache-2.0"
              />
            </div>
          </div>

          <app-dataset-table [datasets]="datasets" />

          <app-author-grid [authors]="authors" />

          <app-article-section />

          <div class="interactive-section">
            <h2 class="section-title">
              Interactive Components
              <span class="badge badge-warning">Working Below Autodetection</span>
            </h2>
            <div class="interactive-grid">
              <app-sortable-list />
              <app-filter-form />
              <app-content-toggles />
              <app-progress-indicators />
            </div>
          </div>

          <app-license-dialog />
        </div>
      </main>

      <app-footer />
    </div>
  `,
  styles: [`
    .research-nexus-app {
      min-height: 100vh;
      background: #fafafa;
    }

    .main-content {
      padding: 32px 24px;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
    }

    .hero-grid {
      display: grid;
      grid-template-columns: 2fr 1fr;
      gap: 24px;
      margin-bottom: 32px;
    }

    .interactive-section {
      margin-bottom: 32px;
    }

    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #212121;
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .badge {
      font-size: 12px;
      font-weight: 600;
      padding: 4px 10px;
      border-radius: 12px;
    }

    .badge-warning {
      background: #fff3e0;
      color: #e65100;
    }

    .interactive-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }
  `],
})
export class ResearchNexusComponent {
  activePage = 'home';

  datasets: Dataset[] = [
    {
      id: '1',
      title: 'KIT Data Metadata Analysis',
      doi: '10.5445/IR/1000185135',
      license: 'https://spdx.org/licenses/MIT',
    },
    {
      id: '2',
      title: 'Research Output Repository Schema',
      doi: '10.5445/IR/1000178054',
      license: 'https://spdx.org/licenses/Apache-2.0',
    },
    {
      id: '3',
      title: 'FDO Implementation Guidelines',
      doi: '10.5445/IR/1000151234',
      license: 'https://spdx.org/licenses/CC-BY-4.0',
    },
  ];

  authors: Author[] = [
    { orcid: '0009-0005-2800-4833', name: 'Maximilian Inckmann', institution: 'Karlsruhe Institute of Technology' },
    { orcid: '0009-0003-2196-9187', name: 'Christopher Raquet', institution: 'Karlsruhe Institute of Technology' },
    { orcid: '0000-0001-6575-1022', name: 'Andreas Pfeil', institution: 'Karlsruhe Institute of Technology' },
  ];

  onNavigate(page: string) {
    this.activePage = page;
  }
}
