// packages/vue-library/demo/components/DatasetTable.vue
<script setup lang="ts">
import { PidComponent } from '../../lib';
import { ref, reactive } from 'vue';

interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

defineProps<{
  datasets: Dataset[];
}>();

const columnWidths = reactive<Record<string, number>>({
  title: 30,
  doi: 30,
  license: 25,
  actions: 15,
});

let resizing: { key: string; startX: number; startWidth: number } | null = null;

function onResizeStart(event: MouseEvent, key: string) {
  event.preventDefault();
  resizing = { key, startX: event.clientX, startWidth: columnWidths[key] };
  document.addEventListener('mousemove', onResizeMove);
  document.addEventListener('mouseup', onResizeEnd);
}

function onResizeMove(event: MouseEvent) {
  if (!resizing) return;
  const table = document.querySelector('.dataset-table-inner') as HTMLElement | null;
  if (!table) return;
  const tableWidth = table.offsetWidth;
  const deltaPercent = ((event.clientX - resizing.startX) / tableWidth) * 100;
  const newWidth = Math.max(5, resizing.startWidth + deltaPercent);
  columnWidths[resizing.key] = newWidth;
}

function onResizeEnd() {
  resizing = null;
  document.removeEventListener('mousemove', onResizeMove);
  document.removeEventListener('mouseup', onResizeEnd);
}
</script>

<template>
  <v-card elevation="1" style="overflow: hidden">
    <v-card-title class="d-flex align-center pa-4 border-b">
      <v-icon color="grey-darken-2" class="mr-2">mdi-file-document</v-icon>
      <span class="text-h6">Related Datasets</span>
    </v-card-title>
    <div style="overflow-x: auto">
      <v-table class="dataset-table-inner elevation-0" style="table-layout: fixed; width: 100%">
        <thead>
        <tr>
          <th
            v-for="col in [
                { key: 'title', label: 'Title' },
                { key: 'doi', label: 'DOI' },
                { key: 'license', label: 'License' },
                { key: 'actions', label: 'Actions' },
              ]"
            :key="col.key"
            :style="{ width: columnWidths[col.key] + '%', position: 'relative', userSelect: 'none' }"
          >
            {{ col.label }}
            <span
              class="resize-handle"
              @mousedown.prevent="onResizeStart($event, col.key)"
            ></span>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="item in datasets" :key="item.id">
          <td style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{ item.title }}</td>
          <td style="overflow: hidden">
            <pid-component :value="item.doi" :emphasize-component="false" style="display: inline-block;" />
          </td>
          <td style="overflow: hidden">
            <pid-component :value="item.license" :emphasize-component="false" style="display: inline-block;" />
          </td>
          <td style="overflow: hidden">
            <v-btn size="small" variant="text" color="primary">View</v-btn>
          </td>
        </tr>
        </tbody>
      </v-table>
    </div>
  </v-card>
</template>

<style scoped>
.resize-handle {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 4px;
  cursor: col-resize;
  background: transparent;
}

.resize-handle:hover {
  background: #90caf9;
}
</style>

// packages/nextjs-app/app/research-nexus/components/DatasetTable.tsx
'use client';

import { FileText } from 'lucide-react';
import { PidComponent } from '@kit-data-manager/react-pid-component';
import { cn } from '../lib/utils';
import { useCallback, useEffect, useRef, useState } from 'react';

interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

interface DatasetTableProps {
  datasets: Dataset[];
  className?: string;
}

const columns = [
  { key: 'title', label: 'Title', initialWidth: 30 },
  { key: 'doi', label: 'DOI', initialWidth: 30 },
  { key: 'license', label: 'License', initialWidth: 25 },
  { key: 'actions', label: 'Actions', initialWidth: 15 },
] as const;

export function DatasetTable({ datasets, className }: DatasetTableProps) {
  const [columnWidths, setColumnWidths] = useState<Record<string, number>>(() =>
    Object.fromEntries(columns.map((c) => [c.key, c.initialWidth])),
  );
  const resizingRef = useRef<{ key: string; startX: number; startWidth: number } | null>(null);
  const tableRef = useRef<HTMLTableElement>(null);

  const onMouseMove = useCallback((e: MouseEvent) => {
    const resizing = resizingRef.current;
    if (!resizing || !tableRef.current) return;
    const tableWidth = tableRef.current.offsetWidth;
    const deltaPercent = ((e.clientX - resizing.startX) / tableWidth) * 100;
    const newWidth = Math.max(5, resizing.startWidth + deltaPercent);
    setColumnWidths((prev) => ({ ...prev, [resizing.key]: newWidth }));
  }, []);

  const onMouseUp = useCallback(() => {
    resizingRef.current = null;
    document.removeEventListener('mousemove', onMouseMove);
    document.removeEventListener('mouseup', onMouseUp);
  }, [onMouseMove]);

  const onResizeStart = useCallback(
    (e: React.MouseEvent, key: string) => {
      e.preventDefault();
      resizingRef.current = { key, startX: e.clientX, startWidth: columnWidths[key] };
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
    },
    [columnWidths, onMouseMove, onMouseUp],
  );

  useEffect(() => {
    return () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
  }, [onMouseMove, onMouseUp]);

  return (
    <div className={cn('rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden', className)}>
      <div className="flex items-center gap-3 p-6 border-b border-slate-100">
        <FileText className="h-5 w-5 text-slate-700" />
        <h2 className="text-lg font-semibold text-slate-900">Related Datasets</h2>
      </div>
      <div style={{ overflowX: 'auto' }}>
        <table ref={tableRef} className="w-full" style={{ tableLayout: 'fixed', width: '100%' }}>
          <thead>
          <tr className="border-b border-slate-100 bg-slate-50/50">
            {columns.map((col) => (
              <th
                key={col.key}
                className="text-left text-xs font-semibold text-slate-500 uppercase tracking-wider px-6 py-3 relative select-none"
                style={{ width: `${columnWidths[col.key]}%` }}
              >
                {col.label}
                <span
                  onMouseDown={(e) => onResizeStart(e, col.key)}
                  className="absolute right-0 top-0 bottom-0 w-1 cursor-col-resize hover:bg-blue-300"
                />
              </th>
            ))}
          </tr>
          </thead>
          <tbody>
          {datasets.map((dataset) => (
            <tr key={dataset.id} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
              <td
                className="px-6 py-4 text-sm text-slate-700 overflow-hidden text-ellipsis whitespace-nowrap">{dataset.title}</td>
              <td className="px-6 py-4 overflow-hidden">
                <PidComponent value={dataset.doi} emphasizeComponent={false} />
              </td>
              <td className="px-6 py-4 overflow-hidden">
                <PidComponent value={dataset.license} emphasizeComponent={false} />
              </td>
              <td className="px-6 py-4 overflow-hidden">
                <button
                  className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-700 transition-colors hover:bg-slate-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-700 disabled:pointer-events-none disabled:opacity-50">
                  View
                </button>
              </td>
            </tr>
          ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
