// packages/angular-library/src/app/components/navigation.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    PidComponent,
  ],
  template: `
    <mat-toolbar class="navigation-toolbar">
      <div class="nav-container">
        <div class="nav-brand">
          <button mat-mini-fab color="primary" disabled>
            <mat-icon>storage</mat-icon>
          </button>
          <span class="brand-text">ResearchDemo</span>
          <mat-chip color="warn" size="small">Demo</mat-chip>
        </div>

        <div class="nav-links">
          <button mat-button [color]="activePage === 'home' ? 'primary' : undefined" (click)="navigate.emit('home')">
            Home
          </button>
          <button mat-button [color]="activePage === 'datasets' ? 'primary' : undefined" (click)="navigate.emit('datasets')">
            Datasets
          </button>
          <button mat-button [color]="activePage === 'about' ? 'primary' : undefined" (click)="navigate.emit('about')">
            About
          </button>

          <span class="nav-divider">|</span>

          <div class="powered-by">
            <span class="powered-text">Powered by</span>
            <pid-component value="https://ror.org/04t3en479" [emphasizeComponent]="false" [hideSubcomponents]="true" />
          </div>
        </div>
      </div>
    </mat-toolbar>
  `,
  styles: [`
    .navigation-toolbar {
      position: sticky;
      top: 0;
      z-index: 100;
      border-bottom: 1px solid #e0e0e0;
      background: white;
    }

    .nav-container {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 24px;
    }

    .nav-brand {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .brand-text {
      font-size: 18px;
      font-weight: 600;
      color: #212121;
    }

    .nav-links {
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .nav-divider {
      margin: 0 16px;
      color: #9e9e9e;
    }

    .powered-by {
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .powered-text {
      font-size: 14px;
      color: #757575;
    }
  `],
})
export class NavigationComponent {
  @Input() activePage = 'home';
  @Output() navigate = new EventEmitter<string>();
}

// packages/nextjs-app/app/research-nexus/components/Navigation.tsx
'use client';

import Link from 'next/link';
import { Database } from 'lucide-react';
import { PidComponent } from '@kit-data-manager/react-pid-component';

export function Navigation() {
  return (
    <nav
      className="sticky top-0 z-50 w-full border-b border-slate-200 bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-600">
              <Database className="h-5 w-5 text-white" />
            </div>
            <span className="text-lg font-semibold text-slate-900">ResearchDemo</span>
            <span
              className="inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">Demo</span>
          </div>
          <div className="flex items-center gap-6">
            <Link href="/research-nexus" className="text-sm text-slate-600 hover:text-slate-900 transition-colors">
              Home
            </Link>
            <Link href="/research-nexus/datasets"
                  className="text-sm text-slate-600 hover:text-slate-900 transition-colors">
              Datasets
            </Link>
            <Link href="/research-nexus/about"
                  className="text-sm text-slate-600 hover:text-slate-900 transition-colors">
              About
            </Link>
            <div className="flex items-center gap-2 border-l border-slate-200 pl-4">
              <span className="text-sm text-slate-500">Powered by</span>
              <PidComponent value="https://ror.org/04t3en479" emphasizeComponent={false} hideSubcomponents={true} />
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}
